### ISSUE TITLE
smooth-scrolling

### ISSUE THREAD

**Issue by VinayBagalakoti** [3kh0/portfolio#1]
I can make scrolling smooth and add a mouse pointer follower

**Comment by 3kh0** [comment]
Ok, if you want to add smooth scrolling that is fine, but making a mouse pointer follower is unneeded.

**Comment by VinayBagalakoti** [comment]
ok i will add smooth scrolling, can you please assign it to me?

**Comment by 3kh0** [comment]
Sure

**Comment by VinayBagalakoti** [comment]
@3kh0 Can u add hacktoberfest label please
